### ISSUE TITLE
Use in databases

### ISSUE THREAD

**Issue by SabrinaJewson** [drifting-in-space/fractional_index#2]
Hi, this crate would be very useful for me for an ordered list stored in a database. But in order to use it for that, I would need a couple extra qualities:

* Direct access to the underlying sequence of bytes to serialize to the database. I _could_ use Serde, but it would be quite some effort and less efficient than accessing the bytes directly.
* Construction from an underlying sequence of bytes to deserialize from the database. Again, while Serde is an option it suffers from the same drawbacks as above.
* Some stability guarantees about the underlying implementation. This could be implemented by somehow versioning `ZenoIndex`es from different versions of the crate, if you think it's possible the actual implementation will still evolve.

Would it be possible to provide these? I would be happy to provide a PR if so.

**Comment by paulgb** [comment]
Hi Sabrina,

Thanks for reaching out.

I'm open to giving direct access to the underlying byte sequence, but I'm curious if [bincode](https://github.com/bincode-org/bincode) meets your needs. I haven't measured it, but would expect it to be minimal in terms of overhead (both of the size of the encoded format and runtime cost).

I like the idea of a stability guarantee. I'd like to leave future versions open to changing the implementation of how ZenoIndexes are constructed, but I think a reasonable guarantee would be something like:
- The ZenoIndex representation itself will not change, so ZenoIndexes created now will be valid for future versions of the crate.
- Comparisons between two particular ZenoIndexes are guaranteed to be stable across versions.

Would that be a suitable guarantee for your use case?

In particular, it would not guarantee that the functions `new_before`, `new_after`, `new_between` would return an identical ZenoIndex across versions, but the semantic guarantees of those methods would be preserved across versions, e.g. if you call `b = new_between(a, c)` on an old version, a new version will still guarantee that `a < b < c` and vice versa, but not the stability of the actual value of `b` returned by both versions being bytewise identical.

**Comment by SabrinaJewson** [comment]
> I'm curious if bincode meets your needs

It would work if I used it, but it still feels suboptimal especially since the actual data is right there. I'd also rather avoid the extra dependency.

> Would that be a suitable guarantee for your use case?

Yes, that would work perfectly.

**Comment by paulgb** [comment]
Published to crates as 1.0.0.

Changes:
- [`from_bytes`](https://docs.rs/fractional_index/1.0.0/fractional_index/struct.ZenoIndex.html#method.from_bytes) constructor.
- [`as_bytes`](https://docs.rs/fractional_index/1.0.0/fractional_index/struct.ZenoIndex.html#method.as_bytes) method.
- [stability note](https://docs.rs/fractional_index/1.0.0/fractional_index/#stability) in readme/docstring.

**Comment by SabrinaJewson** [comment]
Thanks! This will be very useful :D
