### ISSUE TITLE
How to derive a string from ZenoIndex that works with basic lexographic sorting?

### ISSUE THREAD

**Issue by Venryx** [drifting-in-space/fractional_index#3]
The readme contains this section:
> Things get more complicated when one string of bytes is a prefix of the other. Without the first term, our representation would be [lexicographic](https://en.wikipedia.org/wiki/Lexicographic_order) and we could say the shorter one comes before the longer one. Due to the first term, though, the longer one could either be before or after. So we check the following byte to see if it is at most 127 (in which case the longer string comes before its prefix) or not (in which case the longer string comes after).

From this, I gather that simply converting the bytes to a string and then doing a `<` or `>` operation will _not_ allow you to reliably discern the order of two entries. For my use-case, this is a significant negative, because it means that "unsophisticated clients" that receive the order-keys become unable to simply do string comparisons to determine the ordering -- requiring that every third-party client reading data from my GraphQL api be using some version of the `fractional_index` library in their dependencies, even if all they want to do is check the order of a list of returned entries.

So I figured I would raise this issue, to ask two questions:
1) Is there some straightforward way to convert `ZenoIndex` instances into strings that _can_ be lexicographically sorted?
2) If not, is there some "way to use" the library (eg. a wrapper function one could construct) that would avoid producing `ZenoIndex` instances whose string-representations cannot be lexicographically sorted?

I will likely try to build a solution for either 1 or 2 soon (after getting a better handle on the generation/comparison approach being used), but I figured I would mention it here first in case you know of a simple solution to it that can simply be plugged in.

**Comment by paulgb** [comment]
Good questions.

> I gather that simply converting the bytes to a string and then doing a < or > operation will not allow you to reliably discern the order of two entries

Yes, this is correct.

> Is there some straightforward way to convert ZenoIndex instances into strings that can be lexicographically sorted?

I'd have to think about whether this is always correct, but my first instinct is that if you append the byte `128` to every string, I think lexicographical order will work. This only works if _both_ the strings being compared have had the `128` appended. I'm not 100% sure, though, I'll have to think through some examples.

**Comment by paulgb** [comment]
I've published version 1.0.1 to crates.io. This adds a [serialization section](https://github.com/drifting-in-space/fractional_index#serialization) to the readme, describing a new serialization format that serializes to a string which supports lexicographic ordering consistent with the ordering of the ZenoIndex it represents. Does this resolve the issue for you?

**Comment by Venryx** [comment]
Yes that looks like it will work great, thank you!
